name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kivy/buildozer:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build APK with Official Kivy Container
        run: |
          buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MikeyBot-APK
          path: bin/*.apk
