name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Fix Directory Permissions
      run: sudo chmod -R 777 $GITHUB_WORKSPACE

    - name: Build APK with Docker Container
      run: |
        docker run --rm \
          --entrypoint /bin/bash \
          -e BUILDOZER_WARN_ON_ROOT=0 \
          -v ${{ github.workspace }}:/home/user/app \
          kivy/buildozer -c "buildozer android debug"

    - name: Fix Artifact Ownership Permissions
      if: always()
      run: sudo chown -R $USER:$USER .

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mikeybot-apk
        path: bin/*.apk
